### ISSUE TITLE
Does the mod_cfml Valve really need to write mod_cfml.dat?

### ISSUE THREAD

**Issue by pfreitag** [utdream/mod_cfml#13]
I was looking over the code because I got a file permission error when trying to write /var/lib/tomcat7/mod_cfml.dat on Ubuntu (using the Ubuntu tomcat7 installation).

Wouldn't it be better to store the contextRecord array in a static variable instead of in a file since the file is deleted / reset on startup anyways? I realize that this takes memory utilization but it is very small. 

What do you think? If you are ok with switching to a static variable I can submit a pull request with the change.

**Comment by utdream** [comment]
Hey Pete,

A pull request would be great. The original reason it was created as a static file was so that it would persist between restarts, but since that is no longer relevant, a memory-resident variable would probably improve performance and remove the file permission requirement.

Sounds good! Thank you for your help!
