### ISSUE TITLE
wrong webroot with apache virtualhosts on different ports

### ISSUE THREAD

**Issue by zspitzer** [utdream/mod_cfml#17]
just trying to set up a couple of working directories with mod_cfml on windows with apache 2.4

two localhost virtualhosts, on ports 81 and 82
```
<Directory "c:/www/one/">
    Options Indexes FollowSymLinks
    DirectoryIndex index.cfm
    AllowOverride All
    Require all granted
</Directory>

Listen 81
<VirtualHost *:81>
    ServerName  zac-test-one
    DirectoryIndex index.cfm
    DocumentRoot  "C:/www/one/"
	
	<Proxy *>
		#Require host 127.0.0.1
	</Proxy>
	ProxyPreserveHost On
	ProxyPassMatch ^/(.+\.cf[cm])(/.*)?$ ajp://localhost:8009/$1$2
</VirtualHost>


<Directory "c:/www/two/">
    Options Indexes FollowSymLinks
    DirectoryIndex index.cfm
    AllowOverride All
    Require all granted
</Directory>

Listen 82
<VirtualHost *:82>
    ServerName  zac-test-two
    DirectoryIndex index.cfm
    DocumentRoot  "C:/www/two/"
	
	<Proxy *>
		#Require host 127.0.0.1
	</Proxy>
	ProxyPreserveHost On
	ProxyPassMatch ^/(.+\.cf[cm])(/.*)?$ ajp://localhost:8009/$1$2
</VirtualHost>
```
as you can see below, unique X-Tomcat-DocRoot / X-Webserver-Context combinations are generated
```
URI => /one.cfm, filename => proxy:ajp://localhost/one.cfm
Incoming header [Host] => localhost:81
Incoming header [Connection] => keep-alive
Incoming header [Cache-Control] => max-age=0
Incoming header [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3225.0 Safari/537.36
Incoming header [Upgrade-Insecure-Requests] => 1
Incoming header [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Incoming header [DNT] => 1
Incoming header [Accept-Encoding] => gzip, deflate, br
Incoming header [Accept-Language] => en-AU,en;q=0.9,en-US;q=0.8,de;q=0.7
Incoming header [X-Tomcat-DocRoot] => C:/www/one/
Incoming header [X-Webserver-Context] => zac-test-one-httpd-confl554
Handler Pattern Found => .cfm
Pattern Match TRUE: extension [.cfm] matches handler [.cfm]
Handler Pattern Found => .cfc
Handler Pattern Found => .cfml

URI => /two.cfm, filename => proxy:ajp://localhost/two.cfm
Incoming header [Host] => localhost:82
Incoming header [Connection] => keep-alive
Incoming header [Cache-Control] => max-age=0
Incoming header [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3225.0 Safari/537.36
Incoming header [Upgrade-Insecure-Requests] => 1
Incoming header [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Incoming header [DNT] => 1
Incoming header [Accept-Encoding] => gzip, deflate, br
Incoming header [Accept-Language] => en-AU,en;q=0.9,en-US;q=0.8,de;q=0.7
Incoming header [X-Tomcat-DocRoot] => C:/www/two/
Incoming header [X-Webserver-Context] => zac-test-two-httpd-confl575
```

but which ever virtual host gets the first request, the second one just ends up serving from the first host's docroot? have i missed something obvious?

is it that the port is missing from the the proxy:ajp url?
**URI => /two.cfm, filename => proxy:ajp://localhost/two.cfm**

orginally posted here https://dev.lucee.org/t/mod-cfml-woes-with-apache-on-windows/2820

**Comment by utdream** [comment]
Hi Zak,

The issue here is that your host header for both contexts is "localhost". Notice the AJP proxy URL is the same? J2EE contexts have no concept of ports (ports are separated out in Tomcat into <Connector> configs) so they do not affect the context.

For this to work, you'll need two different "host" headers, so that two different contexts get made. Based on your Apache config, you could edit your Windows hosts file (https://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/) to have "zac-test-one" and "zac-test-two" point to 127.0.0.1. Once you've done that, you can type: zac-test-two:82 into your browser, and mod_cfml will create the contexts as "zac-test-one" and "zac-test-two" instead of identical "localhost" contexts. When I do my own local dev work, I usually create my contexts as sitename.local. Otherwise browsers complain that there is no TLD. So maybe try zak1.local and zak2.local instead just for ease of use.

Let me know if that makes sense. I'm probably not explaining it very well.

**Comment by zspitzer** [comment]
There's no way to rewrite the host header to use serverName?

being able to use localhost is important as it's treated as a secure origin
https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only

**Comment by zspitzer** [comment]
i've had some luck with RequestHeader set Host "zac-test-two" which then ends up 
setting the various cgi variables to "zac-test-two" as well

**Comment by utdream** [comment]
Ah! Nice thinking outside of the box there. =)

**Comment by zspitzer** [comment]
Does mod_cfml get involved so I could set x-mod-cfml-host and it could pick that up instead thus leaving the cgi variables untouched or is that all done in mod_proxy world?

**Comment by utdream** [comment]
Anything you set that to will almost certainly be overwritten by the module. I believe the CGI variables are derived by Lucee from the context so I don't think you can actually get around that part without changing how Lucee works.

If your end goal is simply to use geolocation in your development environment, reading the article you posted makes it sound like it might work if the source was SSL-secured. If you, once again, went back to modifying your local "hosts" file so that the domain you're working on resolves locally, you could use your production SSL certificate locally as well, and potentially be able to use GeoLocation from your local machine. Just an idea.

**Comment by zspitzer** [comment]
given it's a limitation of lucee which acf doesn't face, a reasonable tweak to lucee isn't out of the question @michaeloffner?

**Comment by utdream** [comment]
ACF and Lucee are fundamentally different in how they process CFML. Lucee takes a more standard J2EE approach where each web app gets it's own context. ACF operates within a single context and different sites are managed logically. You're asking for a deep, fundamental change in how Lucee works in order to support what is essentially a fringe case.

Even more, there are potentially other ways to accomplish what you're wanting to do. If you don't want to try the SSL approach I mentioned earlier, the following post talks about how to configure both Tomcat and Apache to listen and respond on different ports:
https://stackoverflow.com/questions/8823290/how-to-run-different-apps-on-single-tomcat-instance-behind-different-ports

You'd want to take mod_cfml out of the equation for that kind of config, but you should be able to get the results you're looking for.

Hope this helps!
